version: '3.8'

services:
  kd-prediction:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - /tmp/numba_cache:/tmp/numba_cache
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    deploy:
      resources:
        limits:
          memory: 4G
    restart: unless-stopped 